(function(){
  function tryExtract(){ const result={text:'',subject:'',source:''}; const g=document.querySelector('.ii.gt .a3s')||document.querySelector('.ii.gt'); if(g){ result.text=g.innerText||g.textContent||''; result.source='gmail_read'; const s=document.querySelector('h2.hP')||document.querySelector('.hP'); if(s) result.subject=s.innerText.trim(); return result; } const edit = document.querySelector('[aria-label="Message Body"]')||document.querySelector('[aria-label="Message body"]'); if(edit){ result.text=edit.innerText||edit.textContent||''; result.source='gmail_compose'; const subj=document.querySelector('input[name="subjectbox"]'); if(subj) result.subject=subj.value||''; return result; } const out=document.querySelector('.ReadingPaneContainer')||document.querySelector('[aria-label="Message content"]'); if(out){ result.text=out.innerText||out.textContent||''; result.source='outlook_read'; return result; } const editables = Array.from(document.querySelectorAll('[contenteditable="true"],[role="textbox"]')); for(const el of editables){ const t=el.innerText||el.textContent||''; if(t&&t.length>20&&!/toolbar|menu|button/i.test(el.className||'')){ result.text=t; result.source='generic_editable'; return result; } } return null; }
  function fallback(){ const sel=window.getSelection(); if(sel&&sel.toString().trim().length>20) return {text:sel.toString().trim(),source:'selection'}; const body=document.body?document.body.innerText:''; if(body&&body.trim().length>100) return {text:body.slice(0,20000),source:'page'}; return null; }
  function build(ex){ if(!ex) return null; const p={text:ex.text?ex.text.trim():'',subject:ex.subject||'',source:ex.source||'unknown'}; if(!p.text||p.text.length<20) return null; return p; }
  function setGlobal(p){ if(!p) return; window.__synthex_mail=Object.assign({},p,{detectedAt:new Date().toISOString()}); window.dispatchEvent(new CustomEvent('synthex_mail_changed',{detail:window.__synthex_mail})); }
  function run(){ const prov=tryExtract(); if(prov){ const pl=build(prov); if(pl){ setGlobal(pl); return; } } const fb=fallback(); if(fb){ setGlobal(fb); return; } }
  const obs=new MutationObserver(()=>run()); if(document.body){ obs.observe(document.body,{childList:true,subtree:true}); run(); } else { window.addEventListener('DOMContentLoaded',()=>{ obs.observe(document.body,{childList:true,subtree:true}); run(); }); }
  window.__synthex_helpers={ getMailData:()=>window.__synthex_mail||null, forceDetect:()=>{ run(); return window.__synthex_mail||null; } };
  chrome.runtime.onMessage.addListener((msg,sender,sendResponse)=>{
    if(msg&&msg.type==='EXTRACT_TEXT'){ let walker=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT,null,false); let node; let out=''; while(node=walker.nextNode()){ const t=node.nodeValue.trim(); if(t.length>20) out+=t+'\n'; } sendResponse({text:out}); return true; }
    if(msg&&msg.type==='GET_SELECTION'){ sendResponse({text:window.getSelection().toString()}); return true; }
    if(msg&&msg.type==='GET_MAIL_HELPER'){ sendResponse({mail:window.__synthex_mail||null}); return true; }
  });
})();